name: Build Windows
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build - ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: 'windows-latest'
    steps:
      - uses: actions/checkout@v2
          
      - name: Clone pragma repository
        run: |
          git clone https://github.com/Silverlan/pragma.git
          
      - name: Copy cmake directory
        run: |
          cp -r pragma/cmake $GITHUB_WORKSPACE

      - name: Configure and build with CMake
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DDEPENDENCY_PRAGMA_EXECUTABLE_INCLUDE="../pragma/core/pragma/include/" ..
          cmake --build . --config RelWithDebInfo --target util_udm
          
      - name: Create Release Files
        shell: bash
        run: |
          mkdir release
          cp ./build/RelWithDebInfo/util_udm release/
          
      - name: Release Binaries
        uses: Silverlan/common_actions/release_nightly_binaries@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ github.ref_name }}
          
