name: Build
on:
  push:
    branches: [ master, actions ]
  pull_request:
    branches: [ master, actions ]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows-latest
            name: "Windows x64 MSVC"
            artifact: "Windows-MSVC.tar.xz"
            build_type: "RelWithDebInfo"
            environment_script: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            cc: "cl"
            cxx: "cl"
            archiver: "7z a"
            generators: "Visual Studio 16 2019"
            build_dir: 'build'
          #- os: ubuntu-latest
          #  name: "Ubuntu GCC-11"
          #  artifact: "ubuntu_gcc.7z"
          #  build_type: "RelWithDebInfo"
          #  cc: "gcc-11"
          #  cxx: "g++-11"
          #  archiver: "7z a"
          #  generators: "Unix Makefiles"
          #  build_dir: 'build'

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Setup
        id: setup
        uses: Silverlan/common_actions/setup@actions
        
      - name: Install GCC-11
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install gcc-11 g++-11
          
      - name: Download binaries
        uses: Silverlan/common_actions/download_build_binaries@actions
        continue-on-error: true
        
      - name: Define CMake Variables
        uses: Silverlan/common_actions/define_cmake_var@actions
        with:
          cmake_var: ' -DMATHUTIL_STATIC=ON -DSHAREDUTILS_STATIC=ON -DVFILESYSTEM_STATIC=ON -DUTIL_UDM_STATIC=OFF'
          
      - name: Download submodule - lz4
        uses: Silverlan/common_actions/build_submodule@actions
        with:
          build_target: 'lz4'
          repo: 'https://github.com/lz4/lz4.git'
          repo_name: 'lz4'
          repo_branch: 'release'
          cmake_var: 'DEPENDENCY_LZ4_INCLUDE'
          include_dir: 'lib'
          cmake_script_location: 'third_party_libs/lz4-cmake'

      - name: Download common external libs
        uses: Silverlan/common_actions/get_common_external_libs@actions
          
      - name: CMake Build
        uses: Silverlan/common_actions/build_cmake@actions
        with:
          build_target: util_udm
          build_type: ${{ matrix.config.build_type }}
          build_generator: ${{ matrix.config.generators }}
          
      - name: Upload binaries
        uses: Silverlan/common_actions/upload_build_binaries@actions
        
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: udm-standalone
          retention-days: 30
          path: |
            ${{ matrix.config.build_type }}/util_udm${{ env.GA_SHARED_BINARY_LIBRARY_EXT }}
